### ISSUE TITLE
Pregunta: Como obtuviste esas api GET publicas de esas entidades financieras? Se publica en algun lugar?

### ISSUE THREAD

**Issue by Narvalex** [cabupy/node-cotizaciones#1]

**Comment by carloscarvallo** [comment]
Buenas, por lo que veo en el codigo, se scrapea manualmente cada sitio, en la carpeta modules, esta el scraping para cada sitio

**Comment by Narvalex** [comment]
Gracias @carloscarvallo , en que linea especifica del codigo se inicia el scraping? Disculpa si es una pregunta tonta, pero con javascript no hice nada de lado servidor hasta el momento

**Comment by carloscarvallo** [comment]
fijate el de amambay por ejemplo https://github.com/cabupy/node-cotizaciones/blob/master/modules/amambay.js#L31, con la lib request llama a la url del sitio, al obtener el html de la pagina utiliza cheerio para interactuar con el dom y desde ahi extrae manualmente cada dato que necesita, que necesitas hacer del lado del servidor?

**Comment by Narvalex** [comment]
Gracias @carloscarvallo! En realidad cuando dije que no hago nada lado servidor me refieria a nodejs, que como nunca lo use, no soy muy entendido como para recorrer el codigo, pero ahora que me mostraste la linea especifica para mirar ya puedo ver como puedo hacer mi solucion. Muchas gracias!
